# Generated by Django 2.0.6 on 2018-06-03 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('priceUSD', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CoinInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular coin instance', primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Coin')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular portfolio', primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('coins', models.ManyToManyField(help_text='Select a coins for this portfolio', to='portfolio.CoinInstance')),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.Portfolio')),
            ],
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
