# Generated by Django 2.0.6 on 2018-06-03 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180603_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioinstance',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='portfolioinstance',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='coins',
            field=models.ManyToManyField(help_text='Select a coins for this portfolio', to='portfolio.CoinInstance'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='value',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular portfolio', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='PortfolioInstance',
        ),
    ]
